/**
 * Codegen — orchestration and file emission.
 *
 * Template-first (see ./templates.ts), LLM only as a fallback for clauses no
 * pattern matched. The `origin` recorded on every step makes the split
 * visible: `argus run --mock` reports how many steps were deterministic, which
 * is the point of the design.
 */
import fs from 'node:fs';
import path from 'node:path';
import type { AiClient } from '../shared/ai-client.js';
import type { GeneratedStep, GeneratedTestFile, TestCase } from '../shared/types.js';
import { log } from '../shared/logger.js';
import { compileClause, quote } from './templates.js';

const FALLBACK_SYSTEM_PROMPT = `You translate a single Gherkin clause into one or more Playwright statements.

Rules:
- Output ONLY TypeScript statements. No markdown fences, no commentary, no imports.
- A Playwright \`page\` object and Playwright's \`expect\` are already in scope.
- Every statement must be awaited and end with a semicolon.
- Prefer role- and text-based locators (getByRole, getByText, getByPlaceholder)
  over brittle CSS paths. Use page.locator() when given an explicit selector.
- Emit at most 3 statements.`;

function buildFallbackPrompt(clause: string, testCase: TestCase): string {
  return `Test case: ${testCase.title}
Route under test: ${testCase.targetRoute}

Full scenario for context:
  Given ${testCase.gherkin.given}
  When  ${testCase.gherkin.when}
  Then  ${testCase.gherkin.then}

Translate ONLY this clause into Playwright statements:
"${clause}"`;
}

/** Strip fences/prose and keep plausible statement lines. */
export function sanitizeLlmSnippet(raw: string): string[] {
  return raw
    .replace(/```(?:typescript|ts|javascript|js)?/gi, '')
    .replace(/```/g, '')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .filter((line) => !line.startsWith('import '))
    .filter((line) => line.startsWith('await ') || line.startsWith('//'))
    .slice(0, 3);
}

async function compileWithFallback(
  clause: string,
  testCase: TestCase,
  ai: AiClient | null,
): Promise<GeneratedStep[]> {
  const { steps, unmatched } = compileClause(clause);
  if (unmatched.length === 0) return steps;

  const out = [...steps];
  for (const part of unmatched) {
    if (!ai) {
      out.push({
        source: part,
        code: `// UNRESOLVED (no template matched, LLM fallback unavailable): ${part}`,
        origin: 'template',
        rule: 'unresolved',
      });
      continue;
    }

    const raw = await ai.complete({
      purpose: `codegen fallback: ${part.slice(0, 48)}`,
      system: FALLBACK_SYSTEM_PROMPT,
      user: buildFallbackPrompt(part, testCase),
      maxTokens: 400,
      mockFixture: 'codegen-fallback.txt',
    });

    const lines = sanitizeLlmSnippet(raw);
    if (lines.length === 0) {
      out.push({
        source: part,
        code: `// UNRESOLVED (LLM returned no usable statement): ${part}`,
        origin: 'llm',
        rule: 'unresolved',
      });
      continue;
    }
    for (const line of lines) {
      out.push({ source: part, code: line, origin: 'llm', rule: 'llm-fallback' });
    }
  }
  return out;
}

function renderTestFile(testCase: TestCase, steps: GeneratedStep[]): string {
  const body = steps
    .map((step) => `  // ${step.source}\n  ${step.code}`)
    .join('\n\n');

  return `// ─────────────────────────────────────────────────────────────────────────
// Generated by Argus. Do not edit by hand — regenerate with \`argus run\`.
//
// TestCase.id : ${testCase.id}
// Feature     : ${testCase.featureId}
// Priority    : ${testCase.priority}
// Generated   : ${new Date().toISOString()}
//
// Given ${testCase.gherkin.given}
// When  ${testCase.gherkin.when}
// Then  ${testCase.gherkin.then}
// ─────────────────────────────────────────────────────────────────────────
import { test, expect } from '@playwright/test';

test(${quote(`[${testCase.priority}] ${testCase.title}`)}, async ({ page }) => {
  // Argus tags each test with its TestCase id so the execution engine can map
  // a Playwright result back to the case that produced it.
  test.info().annotations.push({ type: 'argus-test-case-id', description: ${quote(testCase.id)} });

  await page.goto(${quote(testCase.targetRoute)});

${body}
});
`;
}

export interface CodegenOptions {
  outputDir: string;
  /** Null disables the fallback; unmatched clauses become UNRESOLVED comments. */
  ai?: AiClient | null;
  /** Remove previously generated spec files first. Default true. */
  clean?: boolean;
}

export async function generateTests(
  testCases: TestCase[],
  options: CodegenOptions,
): Promise<GeneratedTestFile[]> {
  const { outputDir, ai = null, clean = true } = options;
  fs.mkdirSync(outputDir, { recursive: true });

  if (clean) {
    for (const file of fs.readdirSync(outputDir)) {
      if (file.endsWith('.spec.ts')) fs.unlinkSync(path.join(outputDir, file));
    }
  }

  const generated: GeneratedTestFile[] = [];

  for (const testCase of testCases) {
    const steps: GeneratedStep[] = [];
    for (const clause of [
      testCase.gherkin.given,
      testCase.gherkin.when,
      testCase.gherkin.then,
    ]) {
      steps.push(...(await compileWithFallback(clause, testCase, ai)));
    }

    const fileName = `${testCase.id}.spec.ts`;
    const filePath = path.join(outputDir, fileName);
    const contents = renderTestFile(testCase, steps);
    fs.writeFileSync(filePath, contents, 'utf-8');

    const usedLlmFallback = steps.some((step) => step.origin === 'llm');
    generated.push({
      testCaseId: testCase.id,
      fileName,
      filePath,
      contents,
      steps,
      usedLlmFallback,
    });

    const templateCount = steps.filter((s) => s.origin === 'template').length;
    const marker = usedLlmFallback ? ' (LLM fallback used)' : '';
    log.detail(`${fileName} — ${templateCount}/${steps.length} steps from templates${marker}`);
  }

  return generated;
}

/** Aggregate stats for the run summary line. */
export function codegenStats(files: GeneratedTestFile[]): {
  files: number;
  steps: number;
  templateSteps: number;
  llmSteps: number;
  unresolved: number;
} {
  const steps = files.flatMap((f) => f.steps);
  return {
    files: files.length,
    steps: steps.length,
    templateSteps: steps.filter((s) => s.origin === 'template' && s.rule !== 'unresolved').length,
    llmSteps: steps.filter((s) => s.origin === 'llm').length,
    unresolved: steps.filter((s) => s.rule === 'unresolved').length,
  };
}

export * from './templates.js';
